sudo: required

services:
  - docker

language: python

env:
  - LANG=EN ZABBIX_VERSION=trunk
  - LANG=EN ZABBIX_VERSION=4.2
  - LANG=RU ZABBIX_VERSION=4.2
  - LANG=EN ZABBIX_VERSION=4.0
  - LANG=RU ZABBIX_VERSION=4.0
  - LANG=EN ZABBIX_VERSION=3.4
  - LANG=RU ZABBIX_VERSION=3.4
  - LANG=EN ZABBIX_VERSION=3.2
  - LANG=RU ZABBIX_VERSION=3.2
before_install:
  - python -m pip install py-zabbix
  - pushd tests/docker && docker-compose up -d
  - popd
  - pushd bin
  - while ! python check-api.py; do sleep 5; done
  - popd

install: true

script:
  - pushd bin
  - ./import-templates.py ../out/${ZABBIX_VERSION}/${LANG}/module
  - find ../out/${ZABBIX_VERSION}/${LANG}/* -type d -not -name module -exec ./import-templates.py {} \;
